import { defineRecipe } from '@pandacss/dev';

export const Table = defineRecipe({
  className: '7-Table',
  base: {
    display: 'block',
    borderCollapse: 'collapse',
    position: 'relative',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    backgroundColor: '#fff',
    border: '1px solid #8e8f8f',
    userSelect: 'none',
    color: '#222',
    width: '100%',
    textOverflow: 'ellipsis',
    overflow: 'hidden',

    '& > thead > tr > *': {
      position: 'sticky',
      top: '0',
      height: '25px',
      borderColor: '#f0f0f0',
      background: '#d9ebf9',
      boxSizing: 'border-box',
      fontWeight: 'normal',
      padding: '0 6px',
      _before: {
        boxShadow: 'inset 1px 0 rgba(0, 0, 0, 0.15),inset -1px 0 #fff',
        content: '""',
        height: '70%',
        right: '0',
        pointerEvents: 'none',
        position: 'absolute',
        width: '2px',
      },
      whiteSpace: 'nowrap',
      minWidth: '100px',
      maxWidth: '300px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    '& > tbody > tr > *': {
      userSelect: 'none',

      padding: '0 6px',
      height: '20px',
      paddingTop: '3px',
      paddingBottom: '3px',
      _focus: {
        background: '#cce8f8',
      },
      whiteSpace: 'nowrap',
      minWidth: '100px',
      maxWidth: '300px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },

    '& > tbody > tr': {
      whiteSpace: 'nowrap',
      minWidth: '100px',
      maxWidth: '300px',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      _hover: {
        position: 'sticky',
        overflowX: 'auto',
        top: '0',
        opacity: '1',
        background: 'linear-gradient(180deg, #ffffff, #f0f0f0 90%, #ffffff)',
        borderRadius: 'inherit',
        boxShadow: '0 0 0 1px #b3d3f9',
        borderColor: '#b8d6fb',
        boxSizing: 'border-box',
        fontWeight: 'normal',
        padding: '0 6px',
        transition: 'border-color 0.1s',
        cursor: 'pointer',
      },
      _after: {
        background:
          'linear-gradient(180deg,#e5f4fc,#c4e5f6 30% 50%,#98d1ef 50%,#68b3db )',
        borderRadius: '1px',
        boxShadow: 'inset 0 0 0 2px var(--button-shade-light-active)',
        content: "''",
        height: '100%',
        left: '0',
        margin: '0',
        opacity: '0',
        padding: '0',
        position: 'absolute',
        top: '0',
        transition: 'opacity 0.3s',
        width: '100%',
        zIndex: '-1',
      },
      _active: {
        background: '#cce8f8',
      },
    },
  },
  variants: {
    onHover: {
      true: {
        '& > tbody > tr': {
          _hover: {
            position: 'sticky',
            top: '0',
            opacity: 1,
            background: 'linear-gradient(180deg, #fff9, #e6ecf5cc 90%, #fffc)',
            borderRadius: 'inherit',
            boxShadow: '0 0 0 1px #b3d3f9',
            borderColor: '#b8d6fb',
            boxSizing: 'border-box',
            fontWeight: 'normal',
            padding: '0 6px',
          },
        },
      },
    },
  },
  jsx: ['Root', 'Thread', 'tr', 'th', 'td', 'Tbody'],
});
