import { defineRecipe } from '@pandacss/dev';
export const Button = defineRecipe({
  className: '7-Button',
  base: {
    font: 'var(--font)',
    boxSizing: 'border-box',
    border: 'var(--button-border)',
    borderColor: 'var(--button-border-color)',
    borderRadius: 'var(--border-radius)',
    color: '#222',
    minWidth: '75px',
    minHeight: '23px',
    padding: '0 12px',
    textAlign: 'center',
    background: 'var(--button-gradient)',
    position: 'relative',
    zIndex: 0,
    cursor: 'pointer',
    _before: {
      content: '""',
      position: 'absolute',
      width: '100%',
      height: '100%',
      padding: '0',
      margin: '0',
      top: '0',
      left: '0',
      borderRadius: 'var(--border-radius)',
      background: 'var(--button-gradient-hovered)',
      opacity: 0,
      transition: 'opacity 0.3s',
      zIndex: -1,
    },
    _after: {
      content: '""',
      position: 'absolute',
      width: '100%',
      height: '100%',
      padding: '0',
      margin: '0',
      top: '0',
      left: '0',
      boxShadow: 'var(--button-shadow-active)',
      borderRadius: '2px',
      background: 'var(--button-gradient-active)',
      opacity: 0,
      transition: 'opacity 0.3s',
      zIndex: -1,
    },
    _disabled: {
      background: 'var(--button-face-disabled)',
      borderColor: 'var(--button-border-color-disabled)',
      color: 'var(--button-text-color-disabled)',
      pointerEvents: 'none',
      cursor: 'not-allowed',
    },
    '&:not(:disabled)': {
      cursor: 'pointer',
      _hover: {
        cursor: 'pointer',
        borderColor: 'var(--button-border-color-hovered)',
        transition: 'border-color 0.3s',
        _before: {
          opacity: 1,
          transition: 'opacity 0.3s',
        },
        _active: {
          borderColor: 'var(--button-border-color-active)',
          transition: 'border-color 0.3s',
          _after: {
            opacity: 1,
            transition: 'opacity 0.3s',
          },
        },
      },
    },
    _focusVisible: {
      boxShadow: 'inset 0 0 0 2px var(--button-shade-light-active)',
      outline: '1px dotted #000',
      outlineOffset: '-4px',
    },

    _focus: {
      borderColor: 'var(--button-border-color-default)',
      backgroundImage: 'var(--button-gradient-hovered)',
      animation: '1s ease infinite alternate pulse-anim',
      outline: '1px dotted #000',
      outlineOffset: '-4px',
    },
    _default: {
      borderColor: 'var(--button-border-color-default)',
      backgroundImage: 'var(--button-gradient-hovered)',
      animation: '1s ease infinite alternate pulse-anim',
    },
    '&:not(:disabled), &:not(:hover)': {
      borderColor: 'var(--button-border-color)',
      transition: 'border-color 1s linear',
      _before: {
        opacity: 0,
        transition: 'opacity 1s linear',
      },
    },
  },
  jsx: ['button', 'Button'],
});
